# Overview

What follows are some basic array creation and manipulations, and then an example of creating animations. These are all pretty basic. Make sure to explore some of the links on the wiki for more involved examples.


In [1]:
import numpy as np

In [2]:
# Use a procedure to create an array using 
# a command like Python's "range"
# Arguments are start,stop+1, skip
b = np.arange(7,13,1,dtype=np.int8)
print(b)

[ 7  8  9 10 11 12]


In [3]:
# Specify a simple array of integers
a = np.array([1,2,3,4,5,6],dtype=np.int32)
print(a)

[1 2 3 4 5 6]


In [4]:
# It's often useful to have a range subdivided 
# into many parts...like for plotting
c = np.linspace(1,12,12)
print(c)
# what's the dtype?
print(c.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
float64


In [5]:
# 2D arrays can be specified with lists of lists
d = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float128)
print(d)
# Wow, long doubles!
# How big is it
print(d.size)
# What are the dimensions?
print(d.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
9
(3, 3)


In [6]:
# It's often nice to create arrays of ones or zeros 
# or random numbers

e = np.ones((5,10)) # Argument is tuple of dimensions
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
f = np.zeros((3,4))
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Random floats between [0,1)
g = np.random.random((4,6))
print(g)

[[0.87500999 0.51331916 0.11210989 0.9760666  0.93452688 0.54381902]
 [0.16177319 0.89430094 0.05386343 0.72234733 0.73321626 0.396678  ]
 [0.18718739 0.79538387 0.50438495 0.08875606 0.10227234 0.37162488]
 [0.19120911 0.83836427 0.61162011 0.50456913 0.41926401 0.76787359]]


In [9]:
# Can do tests on matrices
print(g>.5)

[[ True  True False  True  True  True]
 [False  True False  True  True False]
 [False  True  True False False False]
 [False  True  True  True False  True]]


In [10]:
# More control can be provided by where
print(np.where(g>.5,0,1))

[[0 0 1 0 0 0]
 [1 0 1 0 0 1]
 [1 0 0 1 1 1]
 [1 0 0 0 1 0]]


In [11]:
# Even more control with logical 
print(np.where(np.logical_and(g>.25,g<.75),1,0))

[[0 1 0 0 0 1]
 [0 0 0 1 1 1]
 [0 0 1 0 0 1]
 [0 0 1 1 1 0]]


In [20]:
%matplotlib inline
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML # Again, just for notebooks.
plt.style.use('seaborn-pastel')
 
fig = plt.figure()
ax = plt.axes(xlim=(0, 4), ylim=(-2, 2))
line, = ax.plot([], [], lw=3)
plt.close(fig)

def init():
    line.set_data([], [])
    return line,

def animate(i):
    x = np.linspace(0, 4, 1000)
    y = np.sin(2 * np.pi * (x - 0.01 * i))
    line.set_data(x, y)
    return line,
 
anim = FuncAnimation(fig, animate, init_func=init,
                               frames=200, interval=20, blit=True)

In [21]:
HTML(anim.to_html5_video())